-- ============================================================================
-- WeDRIVE - AI Customer Lifecycle & Document Verification
-- Run through Supabase MCP / SQL Editor.
-- API keys remain in settings.ai_keys; these tables store only jobs/results.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.ai_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  event_date DATE,
  description TEXT,
  audience TEXT NOT NULL DEFAULT 'registered_customers',
  subject TEXT,
  body_text TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'ready', 'sending', 'sent', 'failed')),
  generated_by TEXT NOT NULL DEFAULT 'customer_lifecycle_ai',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.ai_notification_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dedupe_key TEXT NOT NULL UNIQUE,
  notification_type TEXT NOT NULL,
  campaign_id BIGINT REFERENCES public.ai_campaigns(id) ON DELETE SET NULL,
  customer_id INTEGER REFERENCES public.customers(id) ON DELETE SET NULL,
  booking_id INTEGER REFERENCES public.bookings(id) ON DELETE SET NULL,
  scheduled_for DATE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed', 'skipped')),
  provider_message_id TEXT,
  error_message TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.document_ai_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL CHECK (document_type IN ('ic_front', 'ic_back', 'license_front', 'license_back', 'form')),
  document_url TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'approved', 'rejected', 'error')),
  extracted_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  confidence NUMERIC(5, 2),
  issues JSONB NOT NULL DEFAULT '[]'::jsonb,
  provider TEXT,
  model TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (customer_id, document_type, document_url)
);

CREATE INDEX IF NOT EXISTS ai_campaigns_event_date_idx
  ON public.ai_campaigns (event_date);

CREATE INDEX IF NOT EXISTS ai_notification_log_status_idx
  ON public.ai_notification_log (status, notification_type, scheduled_for);

CREATE INDEX IF NOT EXISTS document_ai_reviews_customer_idx
  ON public.document_ai_reviews (customer_id, created_at DESC);

ALTER TABLE public.ai_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_notification_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_ai_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can manage AI campaigns" ON public.ai_campaigns;
CREATE POLICY "Admins can manage AI campaigns"
ON public.ai_campaigns FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.admins
    WHERE lower(admins.email) = lower(((select auth.jwt()) ->> 'email'))
      AND lower(admins.role) = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.admins
    WHERE lower(admins.email) = lower(((select auth.jwt()) ->> 'email'))
      AND lower(admins.role) = 'admin'
  )
);

DROP POLICY IF EXISTS "Admins can view AI notification log" ON public.ai_notification_log;
CREATE POLICY "Admins can view AI notification log"
ON public.ai_notification_log FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.admins
    WHERE lower(admins.email) = lower(((select auth.jwt()) ->> 'email'))
      AND lower(admins.role) = 'admin'
  )
);

DROP POLICY IF EXISTS "Admins can manage document AI reviews" ON public.document_ai_reviews;
CREATE POLICY "Admins can manage document AI reviews"
ON public.document_ai_reviews FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.admins
    WHERE lower(admins.email) = lower(((select auth.jwt()) ->> 'email'))
      AND lower(admins.role) = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.admins
    WHERE lower(admins.email) = lower(((select auth.jwt()) ->> 'email'))
      AND lower(admins.role) = 'admin'
  )
);
