-- WeDRIVE - AI Event Planner

CREATE TABLE IF NOT EXISTS public.ai_event_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  region TEXT NOT NULL DEFAULT 'Melaka, Malaysia',
  start_date DATE,
  end_date DATE,
  rationale TEXT,
  suggested_action TEXT,
  confidence NUMERIC(5, 2),
  verification_status TEXT NOT NULL DEFAULT 'needs_review'
    CHECK (verification_status IN ('needs_review', 'verified', 'dismissed')),
  generated_by TEXT NOT NULL DEFAULT 'events_pricing_ai',
  source_notes JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ai_event_suggestions_date_idx
  ON public.ai_event_suggestions (start_date, end_date);

CREATE INDEX IF NOT EXISTS ai_event_suggestions_status_idx
  ON public.ai_event_suggestions (verification_status, start_date);

ALTER TABLE public.ai_event_suggestions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can manage AI event suggestions" ON public.ai_event_suggestions;
CREATE POLICY "Admins can manage AI event suggestions"
ON public.ai_event_suggestions FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM public.admins
    WHERE lower(admins.email) = lower(((select auth.jwt()) ->> 'email'))
      AND lower(admins.role) = 'admin'
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.admins
    WHERE lower(admins.email) = lower(((select auth.jwt()) ->> 'email'))
      AND lower(admins.role) = 'admin'
  )
);
