-- ==============================================================================
-- WeDRIVE - Studio 360 AI Database Setup (Cloudinary)
--
-- Cloudinary stores the image files. Supabase stores only asset metadata and
-- public Cloudinary URLs. This script intentionally does not create a
-- Supabase Storage bucket.
-- ===============================================================================

CREATE TABLE IF NOT EXISTS public.car_visual_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id INTEGER REFERENCES public.cars(id) ON DELETE SET NULL,
  model_key TEXT NOT NULL UNIQUE,
  model_name TEXT NOT NULL,
  category TEXT NOT NULL,
  vin TEXT,
  local_model_path TEXT NOT NULL,
  source_viewer_url TEXT,
  source_listing_url TEXT,
  cdn_prefix TEXT,
  cloudinary_folder TEXT NOT NULL
    CONSTRAINT car_visual_assets_cloudinary_folder_model_check
    CHECK (cloudinary_folder LIKE 'model/%'),
  cloudinary_thumbnail_url TEXT,
  cloudinary_gallery JSONB NOT NULL DEFAULT '[]'::jsonb,
  cloudinary_exterior_frames JSONB NOT NULL DEFAULT '[]'::jsonb,
  cloudinary_interior_faces JSONB NOT NULL DEFAULT '{}'::jsonb,
  frame_count INTEGER NOT NULL DEFAULT 0 CHECK (frame_count BETWEEN 0 AND 200),
  frame_pattern TEXT NOT NULL DEFAULT 'ec/0-{index}.jpg',
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'downloading', 'uploading', 'ready', 'failed')),
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.car_visual_assets'::regclass
      AND conname = 'car_visual_assets_cloudinary_folder_model_check'
  ) THEN
    ALTER TABLE public.car_visual_assets
      ADD CONSTRAINT car_visual_assets_cloudinary_folder_model_check
      CHECK (cloudinary_folder LIKE 'model/%');
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS car_visual_assets_car_id_idx
  ON public.car_visual_assets (car_id);

CREATE INDEX IF NOT EXISTS car_visual_assets_vin_idx
  ON public.car_visual_assets (vin);

CREATE OR REPLACE FUNCTION public.set_car_visual_assets_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

ALTER FUNCTION public.set_car_visual_assets_updated_at()
SET search_path = public;

DROP TRIGGER IF EXISTS car_visual_assets_updated_at
  ON public.car_visual_assets;

CREATE TRIGGER car_visual_assets_updated_at
BEFORE UPDATE ON public.car_visual_assets
FOR EACH ROW
EXECUTE FUNCTION public.set_car_visual_assets_updated_at();

ALTER TABLE public.car_visual_assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read car visual assets"
  ON public.car_visual_assets;
DROP POLICY IF EXISTS "Admins insert car visual assets"
  ON public.car_visual_assets;
DROP POLICY IF EXISTS "Admins update car visual assets"
  ON public.car_visual_assets;
DROP POLICY IF EXISTS "Admins delete car visual assets"
  ON public.car_visual_assets;

CREATE POLICY "Public read car visual assets"
ON public.car_visual_assets
FOR SELECT
TO public
USING (true);

CREATE POLICY "Admins insert car visual assets"
ON public.car_visual_assets
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.admins
    WHERE lower(public.admins.email) = lower((select auth.jwt() ->> 'email'))
      AND lower(public.admins.role) IN ('admin', 'super admin')
  )
);

CREATE POLICY "Admins update car visual assets"
ON public.car_visual_assets
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.admins
    WHERE lower(public.admins.email) = lower((select auth.jwt() ->> 'email'))
      AND lower(public.admins.role) IN ('admin', 'super admin')
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.admins
    WHERE lower(public.admins.email) = lower((select auth.jwt() ->> 'email'))
      AND lower(public.admins.role) IN ('admin', 'super admin')
  )
);

CREATE POLICY "Admins delete car visual assets"
ON public.car_visual_assets
FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.admins
    WHERE lower(public.admins.email) = lower((select auth.jwt() ->> 'email'))
      AND lower(public.admins.role) IN ('admin', 'super admin')
  )
);

ALTER TABLE public.cars
  ADD COLUMN IF NOT EXISTS exterior_frames JSONB;

ALTER TABLE public.cars
  ADD COLUMN IF NOT EXISTS has_360 BOOLEAN DEFAULT false;

ALTER TABLE public.cars
  ADD COLUMN IF NOT EXISTS weekly_price NUMERIC(10, 2),
  ADD COLUMN IF NOT EXISTS monthly_price NUMERIC(10, 2);
